api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    #path('<int:bid_id>', views.listing, name='bid'),
    path('search', views.search, name='search'),
    path('create', views.create, name='create'),
    path('list.json', views.get_rest_list, name='list'),
    #path('listings/<int:pk>/update/', views.ListingUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.listing_delete, name='delete'),
     path('<int:pk>/update/', views.listing_update, name='update'),
    #path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    #path('create', views.ProductCreateView.as_view(), name='create'),
]

w2r/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('bid/', include('bidings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from datetime import datetime
from accounts.models import Seller, Buyer, User
# Create your models here.

'''class Listing(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.DO_NOTHING),
    title = models.CharField(max_length=255),
    address = models.CharField(max_length=255),
    city = models.CharField(max_length=255),
    state = models.CharField(max_length=255),
    zipcode = models.CharField(max_length=255),
    description = models.TextField(blank=True),
    price = models.IntegerField(),
    category = models.CharField(max_length=255),
    quantity = models.CharField(max_length=255),
    delivery = models.CharField(max_length=255),
    dead_line = models.CharField(max_length=255),
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d'),
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True),
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True),
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True),
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True),
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True),
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True),
    is_published = models.BooleanField(default=True),
    list_date = models.DateTimeField(default=datetime.now, blank=True),'''

class Listing(models.Model):
    CATEGORIES = (
        ('CW', 'Construction waste'),
        ('ET', 'Electronics'),
        ('GLS', 'Glass'),
        ('HAZ', 'Hazardous'),
        ('FER', 'Metals'),
        ('HAZ', 'Hazardous'),
        ('MWP', 'Mixed waste products'),
        ('ORG', 'Organic'),
        ('PAC', 'Paper and cardboard'),
        ('MK', 'Plastics'),
        ('RUB', 'Rubber'),
        ('TOB', 'Textiles')
    )

    LIFECYCLES_ = (
        ('A', 'Active'),
        ('B', 'Banned'),
        ('D', 'Due'),
        ('X', 'Adjudicated'),
    )

    title = models.CharField(max_length=255)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    quantity = models.IntegerField()
    category = models.CharField(
        max_length=3,
        choices=CATEGORIES
    )
    date_posted = models.DateTimeField(auto_now_add=True, blank=True)
    seller = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    price = models.IntegerField(default=0)
    is_published = models.BooleanField(default=True)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255 )
    delivery = models.CharField(max_length=255)
    num_bids = models.IntegerField(default=0)
    deadline = models.DateTimeField(auto_now_add=True)
    lifecycle = models.CharField(max_length=1, choices=LIFECYCLES_)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)
    
    def name(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('listing', kwargs={'pk': self.pk})
        
'''class Auction(models.Model):
    listing_id = models.ForeignKey(Listing, on_delete=models.DO_NOTHING)
    number_of_bids = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    time_ending = models.DateTimeField()
    staring_price = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)

class Watchlist(models.Model):
    user_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    auction_id = models.ForeignKey(Auction, on_delete=models.CASCADE)

class Bid(models.Model):
    user_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    auction_id = models.ForeignKey(Auction, on_delete=models.CASCADE)
    bid_time = models.DateTimeField(auto_now_add=True, blank=True)

class Chat(models.Model):
    auction_id = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    time_sent = models.DateTimeField()'''

listings/forms.py
from django import forms
from django.forms import ModelForm
from .models import Listing
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout , Field



class ProductForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'photo_main', 'photo_1', 'photo_2', 'photo_3', 'photo_4', 'photo_5', 'photo_6', 'description', 'quantity', 
                'category', 'price', 'is_published', 'address', 'city', 'zipcode', 'delivery']
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('photo_main', template='baseinput.html')
        )
        self.helper.form_show_labels = False
        self.fields['photo_main'].help_text = None
        self.fields['photo_main'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
        self.fields['photo_1'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
        self.fields['photo_2'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
        self.fields['photo_3'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
        self.fields['photo_4'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
        self.fields['photo_5'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
        self.fields['photo_6'].widget.attrs.update({'placeholder': 'Title', 'class':'form-control-file my-file-input'})
    

listings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Listing
from .choices import price_choices, quantity_choices, state_choices
from django.contrib.auth.decorators import login_required
from accounts.models import User, Seller, Buyer
from accounts.decorators import buyer_required, seller_required
from django.utils import timezone
from .forms import ProductForm
from django.views.generic.edit import FormView, CreateView
from django.utils.decorators import method_decorator
from .models import Listing
from .serializers import ProductSerializer
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages, auth
from django.http import JsonResponse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import permission_classes
from rest_framework.decorators import api_view
from django.views.generic import UpdateView, DeleteView


# Create your views here.

def index(request):
    listings = Listing.objects.order_by('-date_posted').filter(is_published=True)
    paginator = Paginator(listings, 6)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {
        'listings' :paged_listings
    }
    return render(request, 'listings/listings.html', context)

def listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    # seller = get_object_or_404(Seller, first_name=first_name)
    context = {
        'listing':listing,
        # 'seller': seller
    }
    return render(request, 'listings/listing.html', context)

def search(request):
    queryset_list = Listing.objects.order_by('-date_posted')

    # Keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
                 queryset_list = queryset_list.filter(description__icontains=keywords)

    # City
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact=city)

    # State
    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(state__iexact=state)

    # quntity
    if 'quntity' in request.GET:
        quntity = request.GET['quntity']
        if quntity:
            queryset_list = queryset_list.filter(quntity__lte=quntity)

    # Price
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__lte=price)

    context = {
        'state_choices': state_choices,
        'quantity_choices': quantity_choices,
        'price_choices': price_choices,
        'listings': queryset_list,
        'values': request.GET
    }

    return render(request, 'listings/search.html', context)


@login_required
@seller_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['description'] and request.POST['quantity'] and request.FILES['photo_main'] and request.POST['category'] and request.POST['price'] and request.POST['address'] and request.POST['city'] and request.POST['zipcode'] and request.POST['delivery'] :
            product = Listing()
            product.title = request.POST['title']
            product.photo_main = request.FILES['photo_main']
            product.photo_1 = request.FILES.get('photo_1', False)
            product.photo_2 = request.FILES.get('photo_2', False)
            product.photo_3 = request.FILES.get('photo_3', False)
            product.photo_4 = request.FILES.get('photo_4', False)
            product.photo_5 = request.FILES.get('photo_5', False)
            product.photo_6 = request.FILES.get('photo_6', False)
            product.description = request.POST['description']
            product.quantity = request.POST['quantity']
            product.category = request.POST['category']
            product.city = request.POST['city']
            product.zipcode = request.POST['zipcode']
            product.address = request.POST['address']
            product.delivery = request.POST['delivery']
            product.price = request.POST['price']
            
            
            product.seller = request.user
            product.save()
            messages.success(request, 'You are now registered and can log in')
            return redirect('listings')
        else :
            messages.error(request, 'Fill in all the requerd Fields')
            return render(request, 'listings/create.html')
            
    else :
        return render(request, 'listings/create.html')

# @method_decorator(login_required, name='dispatch')
# @method_decorator(seller_required, name='dispatch')
# class ListingDeleteView(DeleteView):
#     model = Listing
#     success_url = '/'
#     template_name = 'listings/listing_confirm_delete.html'
#     def test_func(self):
#         listing = self.get_object()
#         if self.request.user == listing.seller:
#             return True
#         return False


@login_required
@seller_required
def listing_delete(request, pk):
    template = 'listings/listing_confirm_delete.html'
    listing = get_object_or_404(Listing, pk=pk)
    if request.user == listing.seller:
        listing.delete()
        return redirect('listings')
    context = {'listing': listing}
    return render(request, template, context)

@login_required
@seller_required
def listing_update(request, pk):
    instance = get_object_or_404(Listing, pk=pk)
    form = ProductForm(request.POST or None, request.FILES or None, instance=instance)
    if request.user == instance.seller:
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Your Product has been updated successfully')
            return redirect('listings')
    context = {
        'title': instance.title,
        'listing': instance,
        'form': form,
    }
    return render(request, 'listings/update.html', context)    
    


@api_view(['GET'])
@permission_classes((IsAuthenticated, ))
def get_rest_list(request):
    """
    Returns Json list of all restaurants
    """
    if request.method == "GET":
        rest_list = Listing.objects.order_by('-date_posted')
        serializer = ProductSerializer(rest_list, many=True)
        return JsonResponse(serializer.data, safe=False)

class ProductSerializerView(APIView):
    def post(self, request):
        serializer = ProductSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=request.user, status=Invoice.SENT)
        return Response(status=status.HTTP_201_CREATED)

templates/listings/bid.html
{% extends 'base.html' %}

{% block content %}

% block title %} | {{ listing.title }} {% endblock %}

{% endblock %}

templates/listings/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="hero-wrap hero-wrap-0" style="background-image: url({% static '/images/create.jpg' %}); background-size: cover;">
  <div class="overlay"></div>
  <div class="circle-bg"></div>
  <div class="circle-bg-2"></div>
  <div class="container-fluid">
    <div class="row no-gutters d-flex slider-text-0 slider-text align-items-center justify-content-center" data-scrollax-parent="true">
      <div class="col-md-6 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
        <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'index' %}">Home</a></span> <span><a href="{% url 'listings' %}">Listings</a></span></p>
        <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">CREATE</h1>
      </div>
    </div>
  </div>
</div>

<section id="login" class="bg-light py-5">
    <div class="container my-container">
              <h4 class="text-center mb-4 text-primary">
                <i class="fa fa-folder-plus"></i> Create </h4>

            
            {% include 'partials/_alerts.html' %}
            <!-- test -->
{% if error %}
{{ error }}
{% endif %}
<form method="POST" action="{% url 'create' %}" enctype="multipart/form-data">
{% csrf_token %}
<div class="row">
<div class="form-group col">
<input type="text" class="form-control" name="title" placeholder="Title" />
</div>

<div class="form-group col">
  <select name="category" class="select form-control" required="" id="id_category"> <option value="">---------</option> <option value="CW">Construction waste</option> <option value="ET">Electronics</option> <option value="GLS" selected="">Glass</option> <option value="HAZ">Hazardous</option> <option value="FER">Metals</option> <option value="HAZ">Hazardous</option> <option value="MWP">Mixed waste products</option> <option value="ORG">Organic</option> <option value="PAC">Paper and cardboard</option> <option value="MK">Plastics</option> <option value="RUB">Rubber</option> <option value="TOB">Textiles</option>
  </select>
  </div>

  <div class="form-group col">
    <input type="text" class="form-control" placeholder="Quantity" name="quantity" />
    </div>

  <div class="form-group col">
    <input type="text" class="form-control" placeholder="Price" name="price" />
    </div>

  </div>

  <div class="row">
    <div class="form-group col">
    <input type="text" class="form-control" placeholder="Address" name="address" />
    </div>
    
    <div class="form-group col">
    <input type="text" class="form-control" placeholder="City" name="city" />
    </div>
    
    
    <div class="form-group col">
    <input type="text" class="form-control" placeholder="Zipcode" name="zipcode" />
    </div>
    
    <div class="form-group col">
    <input type="text" class="form-control" placeholder="Delivery" name="delivery" />
    </div>
    </div>

<div class="form-group">
  <div class="row">
<label for="photo_main" class="my-label  main-pic ftco-animate fadeInUp ftco-animated">
<input type="file" class="form-control-file my-file-input" name="photo_main" />
<p class="file-return">Main Photo</p>
<i class="fa fa-plus-square my-icon fa-2x"></i>
</label>
</div>
<div class="row">
<label for="photo_1" class="my-label  mr-4 col">
  <input type="file" class="form-control-file my-file-input" name="photo_1" />
  <p class="file-return" >Image 1</p>
  <i class="fa fa-plus-square my-icon fa-2x"></i>
</label>

<label for="photo_2" class="my-label  mr-4 col">
  <input type="file" class="form-control-file my-file-input" name="photo_2" />
  <p class="file-return" >Image 2</p>
  <i class="fa fa-plus-square my-icon fa-2x"></i>
</label>

<label for="photo_3" class="my-label   mr-4 col">
  <input type="file" class="form-control-file my-file-input" name="photo_3" />
  <p class="file-return" >Image 3</p>
  <i class="fa fa-plus-square my-icon fa-2x"></i>
</label>

<label for="photo_4" class="my-label  mr-4 col">
  <input type="file" class="form-control-file my-file-input" name="photo_4" />
  <p class="file-return" >Image 4</p>
  <i class="fa fa-plus-square my-icon fa-2x"></i>
</label>

<label for="photo_5" class="my-label  mr-4 col">
  <input type="file" class="form-control-file my-file-input" name="photo_5" />
  <p class="file-return" >Image 5</p>
  <i class="fa fa-plus-square my-icon fa-2x"></i>
</label>

<label for="photo_6" class="my-label   mr-0 col">
  <input type="file" class="form-control-file my-file-input" name="photo_6" />
  <p class="file-return" >Image 6</p>
  <i  class="fa fa-plus-square my-icon fa-2x"></i>
</label>
</div>
</div>

<div class="form-group">
  <textarea  class="form-control my-textarea" placeholder="Description" name="description" ></textarea>
  </div>





<input class="btn btn-primary py-3 px-5 btn-block mt-3" type="submit" value="Add Product"/> 

</form>

</div>
</section>
{% endblock %}

templates/listings/listing.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %}
{% block title %} | {{ listing.title }} {% endblock %}

{% block content %}
<!-- <div class="js-fullheight"> -->
<div class="hero-wrap hero-wrap-0"
  style="background-image: url({{ listing.photo_main.url }}); background-size: cover; background-repeat: no-repeat; background-position: center center;">
  <div class="overlay"></div>
  <div class="circle-bg"></div>
  <div class="circle-bg-2"></div>
  <div class="container-fluid">
    <div class="row no-gutters d-flex slider-text slider-text-0 align-items-center justify-content-center"
      data-scrollax-parent="true">
      <div class="col-md-6 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
        <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a
              href="{% url 'index' %}">Home</a></span> <span class="mr-2"><a
              href="{% url 'listings' %}">Listings</a></span> <span>{{ listing.title }}</span></p>
        <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">{{ listing.title }}</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section ftco-degree-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12 ftco-animate">
        <h1 class="mb-3 text-center">{{ listing.title }}</h2>

          <div class="tagcloud text-center">
            <a href="" class="tag-cloud-link bg-light">
              <p class="tag-cloud-link">{{ listing.get_category_display }}</p>
            </a>
          </div>
          <hr>

          <div class="one-half align-self-md-end align-self-sm-center">
            <div class="carousel-testimony owl-carousel ftco-owl">
              <div class="item my-img" style="background-image: url({{ listing.photo_main.url }})">
              </div>
              {% if listing.photo_1 %}
              <div class="item my-img">
                <img src="{{ listing.photo_1.url }}" class="img-fluid my-img" alt="">
              </div>
              {% endif %}
              {% if listing.photo_2 %}
              <div class="item my-img" style="background-image: url({{ listing.photo_2.url }})">
              </div>
              {% endif %}
              {% if listing.photo_3 %}
              <div class="item my-img" style="background-image: url({{ listing.photo_3.url }})">
              </div>
              {% endif %}
              {% if listing.photo_4 %}
              <div class="item my-img" style="background-image: url({{ listing.photo_4.url }})">
              </div>
              {% endif %}
              {% if listing.photo_5 %}
              <div class="item my-img" style="background-image: url({{ listing.photo_5.url }})">
              </div>
              {% endif %}
              {% if listing.photo_6 %}
              <div class="item my-img" style="background-image: url({{ listing.photo_6.url }})">
              </div>
              {% endif %}
            </div>
          </div>
          <div class="row py-2 text-secondary text-center">
            <div class="col-2">
              <i class="fas fa-city"></i> City: {{listing.city }}</div>
            <div class="col-2">
              <i class="fas fa-weight-hanging"></i> Quantity: {{listing.quantity }} <small>TON</small></div>
            <div class="col-2">
              <i class="fas fa-truck"></i> {{listing.delivery }}</div>
            <div class="col-2">
              <i class="fas fa-map-marker-alt"></i> ZipCode: {{listing.zipcode }}</div>

            <div class="col-3">
              <i class="fas fa-comment-dollar"></i> Start Price: {{listing.price }} <small>mad</small> </div>
          </div>
          <hr>
          <p>{{ listing.description }}</p>
          {% if user.is_authenticated %}
          {% if user.is_buyer and listing.seller != user %}
          <a href="{% url 'bid' listing.id %}" class="btn btn-primary btn-block">BID</a>
          {% endif %}
          {% if listing.seller == user %}
          <div class="row">
            <div class="col">
              <a id="btn_delete" class="btn btn-danger-1 btn-block mt-1 mb-1"
                href="{% url 'delete' listing.id %}">Delete</a>
            </div>
            <div class="col">
              <a class="btn btn-primary btn-block mt-1 mb-1" href="{% url 'update' listing.id %}">Update</a>
            </div>
          </div>
          {% endif %}
          {% endif %}
          <hr>
          <div class="about-author  bg-light rounded text-center">

            <h3 class="text-center">{{ listing.seller }}</h3>
          </div>

          <!-- Description -->


          <!-- </div>
      <div class="col-md-3">
        <div class="card mb-3">
          <img class="card-img-top" src="" alt="Seller of the month">
          <div class="card-body text-center">
            <h5 class="card-title">Seller</h5>
            <a href="{% url 'profile' slug=request.user.id %}">
              <h6 class="text-secondary">{{ listing.seller.first_name }}</h6>
            </a>
          </div>
        </div>
        {% if user.is_buyer %}
        <a href="{% url 'bid' listing.id %}" class="btn-secondary btn-block btn-lg" role="button" aria-pressed="true"
          style="text-align: center;">Bid Now</a>
        {% endif %}
        {% if listing.seller == user %}
        <div>

          {% comment %} <a class="btn btn-danger btn-lg mt-1 mb-1" onclick="return JSalert()" href="">dDelete</a>
          {% endcomment %}
        </div>
        {% endif %}
      </div>
    </div>
  </div> -->


</section>
{% comment %} <script type="text/javascript">
  function JSalert() {
    swal({
        title: "Are you sure?",
        text: "Once deleted, you will not be able to recover this imaginary file!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      })
      .then((willDelete) => {
        if (willDelete) {
          swal("Poof! Your imaginary file has been deleted!", {
            icon: "success",
          });
        } else {
          swal("Your imaginary file is safe!");
        }
      });
  }
</script> {% endcomment %}

{% endblock %}

templates/listings/listing_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ listing.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'listings' listing.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}